name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Prettier
      run: npx prettier --write .
      
    - uses: stefanzweifel/git-auto-commit-action@v5
