name: Code Quality

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pint:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: composer:v2
                  coverage: xdebug

            - name: Cache Vendor
              id: cache-vendor
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

            - name: Install Dependencies
              if: steps.cache-vendor.outputs.cache-hit != 'true'
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Run Laravel Pint
              run: vendor/bin/pint

            - uses: stefanzweifel/git-auto-commit-action@v5
